name: Component tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          browser: chrome

      - name: Store test results
        if: always()  # This ensures results are stored even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results  # Adjust the path according to where Cypress stores results
